### ISSUE TITLE
Support for SVG

### ISSUE THREAD

**Issue by dieggsy** [franzinc/aserve#13]
I tried defining an svg using keyword tags within a `net.html.generator:html` and got an "unknown html keyword" error. I sort of got around this by using the internal:

```lisp
(net.html.generator::def-std-html :svg t nil)
(net.html.generator::def-std-html :g t nil)
(net.html.generator::def-std-html :text t nil)
(net.html.generator::def-std-html :rect t nil)
;; ... etc.
```

But it would be nice to support this by default or to make def-std-html external for this purpose.

**Comment by kmcgivney** [comment]
I did a diff between the keys of `*html-process-table*` and the list here: https://www.w3schools.com/tags/default.asp. The full list of missing tags seems to be **svg**, **picture**, **summary**, and **template**. There were also a few deprecated and invalid tags supported by the html generator, though I suppose this is less of an issue.
