### ISSUE TITLE
Googling AllegroServe still comes up with the SourceForge origin

### ISSUE THREAD

**Issue by MadaraUchiha** [franzinc/aserve#3]
Not strictly related to the code, but more to the project in general.

I was looking for the source code for AllegroServe, and had to dig up quite a bit before I found this repo. The first page I found was this http://allegroserve.sourceforge.net/ which looks outdated and/or misleading, as you probably know, SourceForge is a known malware distributor.

I propose the creation of a GitHub pages branch for the project, with all the information expected of an open source project:

- Link to source code
- How to raise issues
- How to contribute code (code of conduct, code style, etc)

WDYT?

**Comment by franzinc** [comment]
I just added a redirect for sf.net to github.com.
